/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package incubasys.needcharge.datainterfaces.models

import org.joda.time.DateTime


/**
 *
 * @param id
 * @param url
 * @param createdAt */
data class Document(
        val id: Int,
        val url: String,
        val createdAt: DateTime
) {

}


