/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package incubasys.needcharge.datainterfaces.models


/**
 *
 * @param id
 * @param orderNumber
 * @param amount
 * @param paymentType 0 => Credit Card 1 => Paypal
 */
data class Order(
        val id: Int,
        val orderNumber: String,
        val amount: java.math.BigDecimal,
        /* 0 => Credit Card 1 => Paypal */
        val paymentType: Int

) {
}