/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package incubasys.needcharge.datainterfaces.models


/**
 *
 * @param timestamp
 * @param pageSize
 * @param moreAvailable
 * @param totalRecords
 * @param page
 * @param totalPages
 */
data class PageInfo(

        val timestamp: java.time.LocalDateTime? = null,
        val pageSize: Int? = null,
        val moreAvailable: Boolean? = null,
        val totalRecords: Int? = null,
        val page: Int? = null,
        val totalPages: Int? = null
) {
}