/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package incubasys.needcharge.datainterfaces.models

import com.google.gson.annotations.SerializedName


/**
 *
 * @param phone
 * @param countryCode
 * @param verificationCode
 */
data class PhoneUpdate(
        val phone: String,
        @SerializedName("country_code")
        val countryCode: String,
        @SerializedName("verification_code")
        val verificationCode: String

) {
}