/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package incubasys.needcharge.datainterfaces.models


/**
 *
 * @param id
 * @param terms
 * @param privacyPolicy
 */
data class SupportContentOutput(
        val id: Int,
        val terms: String? = null,
        val privacyPolicy: String? = null
) {
}